name: campusbite_v1
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # UI and Animations
  smooth_page_indicator: ^1.0.0+2
  cupertino_icons: ^1.0.8
  lottie: ^3.3.1 # Updated to the latest version

  # Biometric Authentication
  local_auth: ^2.1.1

  # Firebase Integration (Authentication, Firestore, etc.)
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5

  # State Management
  provider: ^6.0.0

  # HTTP Requests (for API calls)
  http: ^1.3.0

  # Local Storage (for caching or small data)
  shared_preferences: ^2.2.0

  # Form Validation
  flutter_form_builder: ^8.0.0

  # AI Chatbot (Dialogflow or OpenAI)
  #dialogflow_grpc: ^0.1.0 # For Dialogflow integration
  # openai: ^1.0.0 # For OpenAI integration (uncomment if needed)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  assets:
    - assets/onboarding1.jpeg
    - assets/onboarding2.jpeg
    - assets/onboarding3.jpeg
    - assets/logo.png
    - assets/animations/burger.json
    - assets/animations/phone_food.json
    - assets/animations/student_eating.json
    - assets/animations/food_delivery.json